apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
spec:
  project: default
  source:
    repoURL: 'https://github.com/dhpup/image-updater-app'
    path: apps
    targetRevision: HEAD
  destination:
    namespace: argocd
    name: in-cluster
  syncPolicy: {}
