apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
spec:
  generators:
  - matrix:
      generators:
      - clusters:
          selector:
            matchLabels:
              apps: 'enabled'
      - git:
          repoURL: https://github.com/dhpup/image-updater-app.git
          revision: HEAD
          directories:
          - path: clusters/apps/*
  template:
    metadata:
      name: '{{path.basename}}-{{name}}'
      annotations:
        argocd-image-updater.argoproj.io/image-list: guestbook=dhpup/guestbook
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/write-back-target: kustomization
        argocd-image-updater.argoproj.io/guestbook.update-strategy: latest
        argocd-image-updater.argoproj.io/guestbook.allow-tags: regexp:^sha-[0-9a-f]{7}$
        argocd-image-updater.argoproj.io/argocd.force-update: 'true'
    spec:
      destination:
        namespace: '{{path.basename}}'
        server: '{{server}}'
      source:
        repoURL: https://github.com/dhpup/image-updater-app.git
        targetRevision: HEAD
        path: '{{path}}'
      project: apps
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
